Repository founder-srm/IdeaClinic-Mobile, pull requests merged in 2025-03, with the labels that each got.

#1 V1.1.0 First Release
  .prettierignore
  README.md
  actions/forum/profile.ts
  app.json
  app/(auth)/_layout.tsx
  app/(auth)/login.tsx
  app/(auth)/signup.tsx
  app/(forum)/_layout.tsx
  app/(forum)/account/[id].tsx
  app/(forum)/forum.tsx
  app/(forum)/post/[slug].tsx
  app/(forum)/post/new.tsx
  app/(settings)/_layout.tsx
  app/(settings)/settings.tsx
  app/_layout.tsx
  app/details.tsx
  app/index.tsx
  assets/background/auth-bg.svg
  assets/icons/heart.png
  assets/icons/logout.png
  assets/icons/menu.png
  assets/icons/search.png
  assets/icons/settings.png
  assets/logo.png
  bun.lockb
  components.json
  components/EnhancedAvatarHeader.tsx
  components/ForumPostsList.tsx
  components/auth/AuthAlert.tsx
  components/auth/AuthBackground.tsx
  components/auth/BackgroundSVG.tsx
  components/cloudinary/CloudinaryUploader.tsx
  components/ui/alert-dialog.tsx
  components/ui/button.tsx
  components/ui/card.tsx
  components/ui/input.tsx
  components/ui/label.tsx
  components/ui/select.tsx
  components/ui/separator.tsx
  components/ui/text.tsx
  components/ui/textarea.tsx
  database.types.ts
  hooks/useSignOut.ts
  hooks/useUser.ts
  lib/icons/Check.tsx
  lib/icons/ChevronDown.tsx
  lib/icons/ChevronUp.tsx
  lib/useKeyboard.tsx
  lib/utils.ts
  package.json
  prettier.config.js
  providers/AuthProvider.tsx
  store/store.ts
  utils/config.ts
  utils/dimensions.ts
  utils/supabase.ts
Labels: documentation, enhancement, good first issue, help wanted

#12 Post details page and post creation UI
  app/(forum)/post/[slug].tsx
  app/(forum)/post/new.tsx
  lib/icons/Slug.tsx
Labels: enhancement, good first issue, help wanted

#14 Created Public Profile View
  app/(forum)/_layout.tsx
  app/(forum)/account/[id].tsx
Labels: enhancement, good first issue, help wanted

#15 search and pull to refresh
  app/(forum)/forum.tsx
Labels: enhancement, good first issue

#16 Accounts page fixed
  app/(forum)/about.tsx
  app/(forum)/account/[id].tsx
  app/(forum)/post/[slug].tsx
  app/(forum)/support.tsx
  app/(settings)/settings.tsx
Labels: enhancement, good first issue, help wanted
